set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN R2 [get_ports en]
set_property PACKAGE_PIN L1 [get_ports done]
set_property IOSTANDARD LVCMOS33 [get_ports done]
set_property IOSTANDARD LVCMOS33 [get_ports en]

set_property IOSTANDARD LVCMOS33 [get_ports {visited[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {visited[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {visited[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {visited[0]}]
set_property PACKAGE_PIN V19 [get_ports {visited[3]}]
set_property PACKAGE_PIN U19 [get_ports {visited[2]}]
set_property PACKAGE_PIN E19 [get_ports {visited[1]}]
set_property PACKAGE_PIN U16 [get_ports {visited[0]}]
